# Generated by Django 6.0.3 on 2026-03-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=54)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=54)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=54)),
                ('abreviacao', models.CharField(db_column='tx_abbreviation', max_length=2)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='tx_description', max_length=54)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civis',
                'db_table': 'marital_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='tx_description', max_length=54)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'means_payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='tx_description', max_length=54)),
                ('percentual_comissao', models.DecimalField(db_column='nb_commission_percentage', decimal_places=4, max_digits=10)),
                ('percentual_ganho', models.DecimalField(db_column='nb_gain_percentage', decimal_places=4, max_digits=10)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
            ],
            options={
                'verbose_name': 'Grupo de Produto',
                'verbose_name_plural': 'Grupos de Produtos',
                'db_table': 'product_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=54)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=54)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('cidade', models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.DO_NOTHING, related_name='distritos', to='principal.cidade')),
                ('zona', models.ForeignKey(db_column='id_zone', on_delete=django.db.models.deletion.DO_NOTHING, related_name='distritos', to='principal.zona')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'district',
                'managed': True,
                'unique_together': {('zona', 'cidade', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(db_column='id_state', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cidades', to='principal.estado'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=54)),
                ('salario', models.DecimalField(db_column='nb_salary', decimal_places=4, max_digits=10)),
                ('genero', models.CharField(db_column='cs_gender', max_length=1)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('distrito', models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes', to='principal.distrito')),
                ('estado_civil', models.ForeignKey(db_column='id_marital_status', on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes', to='principal.estadocivil')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=54)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('distrito', models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.DO_NOTHING, related_name='filiais', to='principal.distrito')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'db_table': 'branch_office',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FornecedorProduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=54)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('distrito', models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_produto', to='principal.distrito')),
            ],
            options={
                'verbose_name': 'Fornecedor de Produto',
                'verbose_name_plural': 'Fornecedores de Produtos',
                'db_table': 'supplier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=54)),
                ('salario', models.DecimalField(db_column='nb_salary', decimal_places=4, max_digits=10)),
                ('admissao', models.DateField(db_column='dt_adminission')),
                ('nascimento', models.DateField(db_column='dt_birth')),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('departamento', models.ForeignKey(db_column='id_department', on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcionarios', to='principal.departamento')),
                ('estado_civil', models.ForeignKey(db_column='id_marital_status', on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcionarios', to='principal.estadocivil')),
                ('gerente', models.ForeignKey(blank=True, db_column='id_manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='principal.funcionario')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='tx_name', max_length=104)),
                ('preco_custo', models.DecimalField(db_column='nb_cost_price', decimal_places=4, max_digits=10)),
                ('preco_venda', models.DecimalField(db_column='nb_sale_price', decimal_places=4, max_digits=10)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('fornecedor_produto', models.ForeignKey(db_column='id_supplier', on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='principal.fornecedorproduto')),
                ('grupo_de_produto', models.ForeignKey(db_column='id_product_group', on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='principal.grupoproduto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendido_em', models.DateTimeField(blank=True, db_column='dt_sale', null=True)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('cliente', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendas', to='principal.cliente')),
                ('filial', models.ForeignKey(db_column='id_branch_office', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendas', to='principal.filial')),
                ('funcionario', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendas', to='principal.funcionario')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'sale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(db_column='nb_value', decimal_places=4, max_digits=10)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('forma_pagamento', models.ForeignKey(db_column='id_means_payment', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagamentos_das_vendas', to='principal.formapagamento')),
                ('venda', models.ForeignKey(db_column='id_sale', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagamentos_das_venda', to='principal.venda')),
            ],
            options={
                'verbose_name': 'Pagamento da Venda',
                'verbose_name_plural': 'Pagamentos das Vendas',
                'db_table': 'means_payment_sale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(db_column='nb_quantity', decimal_places=3, max_digits=10)),
                ('preco_venda', models.DecimalField(db_column='nb_sale_price', decimal_places=4, max_digits=10)),
                ('subtotal', models.DecimalField(db_column='nb_subtotal', decimal_places=4, max_digits=10)),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modificado_em', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('produto', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, related_name='items_venda', to='principal.produto')),
                ('venda', models.ForeignKey(db_column='id_sale', on_delete=django.db.models.deletion.DO_NOTHING, related_name='items_venda', to='principal.venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Vendas',
                'db_table': 'sale_item',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('estado', 'nome')},
        ),
    ]
