# Generated by Django 6.0.3 on 2026-04-02 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Statuses',
                'db_table': 'marital_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeansPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=64)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
            ],
            options={
                'verbose_name': 'Means Payment',
                'verbose_name_plural': 'Means Payments',
                'db_table': 'means_payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('commission_percentage', models.DecimalField(db_column='commission_percentage', decimal_places=2, max_digits=5)),
                ('gain_percentage', models.DecimalField(db_column='gain_percentage', decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'db_table': 'product_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('abbreviation', models.CharField(db_column='abbreviation', max_length=2)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('legal_document', models.CharField(db_column='legal_document', max_length=20)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'zone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('city', models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='principal.city')),
                ('zone', models.ForeignKey(db_column='id_zone', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='principal.zone')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'district',
                'managed': True,
                'unique_together': {('zone', 'city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('district', models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.CASCADE, related_name='branch_offices', to='principal.district')),
            ],
            options={
                'verbose_name': 'Branch Office',
                'verbose_name_plural': 'Branch Offices',
                'db_table': 'branch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('salary', models.DecimalField(db_column='salary', decimal_places=2, max_digits=16)),
                ('admission', models.DateField(db_column='admission_date')),
                ('birth', models.DateField(db_column='birth_date')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], db_column='gender', max_length=1)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('department', models.ForeignKey(db_column='id_department', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='principal.department')),
                ('district', models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='principal.district')),
                ('marital_status', models.ForeignKey(db_column='id_marital_status', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='principal.maritalstatus')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('income', models.DecimalField(db_column='income', decimal_places=2, max_digits=16)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], db_column='gender', max_length=1)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('district', models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='principal.district')),
                ('marital_status', models.ForeignKey(db_column='id_marital_status', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='principal.maritalstatus')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('cost_price', models.DecimalField(db_column='cost_price', decimal_places=2, max_digits=16)),
                ('sale_price', models.DecimalField(db_column='sale_price', decimal_places=2, max_digits=16)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('product_group', models.ForeignKey(db_column='id_product_group', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='principal.productgroup')),
                ('supplier', models.ForeignKey(db_column='id_supplier', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='principal.supplier')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sold_at', models.DateTimeField(db_column='date')),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('branch_office', models.ForeignKey(db_column='id_branch', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='principal.branchoffice')),
                ('customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='principal.customer')),
                ('employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='principal.employee')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=3, max_digits=16)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='principal.product')),
                ('sale', models.ForeignKey(db_column='id_sale', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='principal.sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'db_table': 'sale_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='value', decimal_places=2, max_digits=16)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('means_payment', models.ForeignKey(db_column='id_means_payment', on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='principal.meanspayment')),
                ('sale', models.ForeignKey(db_column='id_sale', on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='principal.sale')),
            ],
            options={
                'verbose_name': 'Sale Payment',
                'verbose_name_plural': 'Sale Payments',
                'db_table': 'means_payment_sale',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='id_state', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='principal.state'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
    ]
