# Generated by Django 6.0.3 on 2026-03-30 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='district',
            field=models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.CASCADE, related_name='branch_offices', to='principal.district'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='id_state', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='principal.state'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='principal.district'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.ForeignKey(db_column='id_marital_status', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='principal.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='principal.city'),
        ),
        migrations.AlterField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(db_column='id_zone', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='principal.zone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(db_column='id_department', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='principal.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.ForeignKey(db_column='id_marital_status', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='principal.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(db_column='id_product_group', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='principal.productgroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(db_column='id_supplier', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='principal.supplier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch_office',
            field=models.ForeignKey(db_column='id_branch_office', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='principal.branchoffice'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='principal.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='principal.employee'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='principal.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(db_column='id_sale', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='principal.sale'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='means_payment',
            field=models.ForeignKey(db_column='id_means_payment', on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='principal.meanspayment'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='sale',
            field=models.ForeignKey(db_column='id_sale', on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='principal.sale'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='district',
            field=models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='principal.district'),
        ),
    ]
