# Generated by Django 6.0.3 on 2026-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_customer_gender_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(db_column='total_amount', decimal_places=2, default=0, max_digits=16),
        ),
    ]
