# Generated by Django 6.0.3 on 2026-04-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_sale_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_column='email', default='example@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
